{% set name = "binpacking" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a79bfb41f24289ef2fb343516f21c1de2effd4d8dfc5adee46d514da706446f4

build:
  number: 0
  entry_points:
    - binpacking = binpacking.binpacking_binary:main
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir

requirements:
  host:
    - pip
    - python
    - pytest-runner
  run:
    - pip
    - python
    - numpy
    - future

test:
  imports:
    - binpacking
  commands:
    - binpacking --help

about:
  home: https://www.github.com/benmaier/binpacking
  license: MIT
  license_family: MIT
  license_file: LICENSE.in
  summary: Heuristic distribution of weighted items to bins (either a fixed number of bins or a fixed number of volume per bin). Data may be in form of list, dictionary, list of tuples or csv-file.

extra:
  recipe-maintainers:
    - benmaier
    - pirovc
